    - name: Install Nginx
      dnf:
        name: "{{ nginx_package }}"
        state: present
    - name: Start nginx
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: true
    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx 
