    - name: Install Nginx
      dnf:
        name: "{{ nginx_package }}"
        state: present
    - name: Start nginx
      service:
        name: "{{ nginx_service }}"
        state: started
        enabled: true
