- name: Install Mariadb
  dnf:
    name: "{{ mariadb_package }}"
    state: present

- name: Start Mariadb
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: "{{ mariadb_root_password }}"
