---
- name: Install PHP and PHP-FPM
  dnf:
    name:
      - "{{ php_package }}"
      - "{{ php_fpm_package }}"
    state: present

- name: Start PHP-FPM
  service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: true
